### ISSUE TITLE
Fluentd 容器无法启动：日志文件权限问题

### ISSUE THREAD

**Issue by kmfb** [OpenCSGs/csghub#980]
描述问题
在使用 docker-compose 启动 CSGHub 服务时，fluentd 容器无法正常启动，导致其他依赖服务也无法正常运行。错误显示 fluentd 无法写入日志文件。
环境信息
CSGHub 版本: v1.4.0
2025-02-28 02:31:30 +0000 [info]: init supervisor logger path=nil rotate_age=nil rotate_size=nil
2025-02-28 02:31:30 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2025-02-28 02:31:30 +0000 [info]: gem 'fluentd' version '1.16.7'
2025-02-28 02:31:30 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="out_file: `/fluentd/log/nats.20250228.log.gz` is not writable"

排查过程
通过检查容器内部文件权限，发现 /fluentd/log 目录属于 fluent 用户：
/ $ ls -la /fluentd/
total 20
drwxr-xr-x    1 fluent   fluent        4096 Feb  3 22:27 .
drwxr-xr-x    1 root     root          4096 Feb 28 02:32 ..
drwxr-xr-x    1 fluent   fluent        4096 Feb  3 22:27 etc
drwxr-xr-x    2 fluent   fluent        4096 Feb  3 22:27 log
drwxr-xr-x    2 fluent   fluent        4096 Feb  3 22:27 plugins

尝试使用 chmod 777 /fluentd/log 修改权限，但容器重启后权限设置没有保留。

**Comment by Yiling-J** [comment]
@kmfb thank you for the detailed problem description and the debug information! @MasonXon @wayneliu0019, could you please take a look and confirm whether this is a bug?

**Comment by MasonXon** [comment]
什么系统下运行的？

**Comment by kmfb** [comment]
> 什么系统下运行的？

~/csghub/csghub$ uname -a
Linux haiyiai-develop-intelnal-gpu-server-01 5.15.0-130-generic #140-Ubuntu SMP Wed Dec 18 17:59:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

另外启动intall脚本文件的时候用的sudo，请问会不会是sudo导致的呢

**Comment by wayneliu0019** [comment]
请检查下您的部署脚本中fluentd service有 `privileged: true`和`user: "root"`关键字，类似如下：

```
 fluentd:
    image: ${CSGHUB_IMAGE_PREFIX}/fluentd:v1.16-1
    ports:
      - "24224:24224"
    volumes:
      - ./configs/fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./logs/fluentd/archived:/fluentd/log
      - ./logs/fluentd/buffer:/fluentd/buffer
    restart: always
    privileged: true
    user: "root"
    healthcheck:
      test: [ "CMD-SHELL", "nc -z fluentd 24224" ]
      interval: 10s
      timeout: 30s
      retries: 30
    networks:
      opencsg:
        ipv4_address: 192.171.100.124
```

或者干脆把宿主机上挂载目录权限都更改为777:    chmod -R 777 ./logs
